# Generated by Django 4.1.2 on 2022-10-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='calaries_count',
            new_name='calories_count',
        ),
    ]
